apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: example
spec:
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
  replicas: 4
