apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/peam1146/argo-app-example.git
    targetRevision: HEAD
    path: app/k8s
    directories:
      recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: my-app
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
